version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/html
    ports:
      - 8080:80
    networks:
      - default

  php-cli:
    build:
      context: .
      dockerfile: .docker/php-cli/Dockerfile
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ~/.composer/auth.json:/root/.composer/auth.json:ro
      - .:/var/www/html

